AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  IngressCIDR:
    Type: String
    Description: The CIDR range for inbound access. (Point to the Internet.)
    Default: 0.0.0.0/0

  EngressCIDR:
    Type: String
    Description: The CIDR range for outbound access. (Point to ECS cluster.)
    Default: 0.0.0.0/0

  KeypairName:
    Type: String
    Description: The name of the EC2 key pair to associate with the instance.
    Default: SNMKeypair

  AMI:
    Type: String
    Description: The AMI to use for the instance.
    Default: ami-058bd2d568351da34

Resources:
  ReverseProxyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType: t2.micro
      KeyName: !Ref KeypairName
      SecurityGroupIds:
        - !Ref ReverseProxySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update and install Nginx
          sudo apt-get update
          sudo apt-get install -y nginx

          # Display Nginx version
          sudo nginx -v

          # Create reverse_proxy configuration file
          echo 'server {
              listen 80;
              server_name 3.87.247.171;

              location / {
                  proxy_pass http://3.87.247.171:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }' | sudo tee /etc/nginx/sites-available/reverse_proxy.conf

          # Create a symbolic link to enable the reverse_proxy configuration
          sudo ln -s /etc/nginx/sites-available/reverse_proxy.conf /etc/nginx/sites-enabled/

          # Disable the default configuration
          sudo rm /etc/nginx/sites-enabled/default

          # Create a nodeapp configuration in conf.d
          echo 'server {
              listen 80;
              server_name 3.87.247.171;

              location / {
                  proxy_pass http://3.87.247.171:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }' | sudo tee /etc/nginx/conf.d/nodeapp.conf

          # Reload Nginx to apply changes
          sudo nginx -s reload

          # Display status after setup
          sudo systemctl status nginx.service

  ReverseProxySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for the Nginx reverse proxy
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref IngressCIDR
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref IngressCIDR
