AWSTemplateFormatVersion: 2010-09-09
Parameters:
  APIElasticIP:
    Type: String
    Description: The Elastic IP address to use for the API.
  APIImageLocation:
    Type: String
    Description: The location of the API Docker image to use in ECS.
    Default: 123456789012.dkr.ecr.region.amazonaws.com/image:tag
  AppName:
    Type: String
    Description: Used to name the ECS cluster.
  ClusterSubnetA:
    Type: AWS::EC2::Subnet::Id
    Description: The subnet where the ECS cluster will be deployed.
  ClusterSubnetB:
    Type: AWS::EC2::Subnet::Id
    Description: The subnet where the ECS cluster will be deployed.
  DatabaseUrl:
    Type: String
    Description: The URL of the database to use in the application.
    Default: postgresql://username:password@localhost:5432/databasename?schema=public
  ECSTaskExecutionRole:
    Type: String
    Description: The ARN of the ECS task execution role.
  Environment:
    Type: String
    Description: Environment name.
    Default: Development
  ProjectName:
    Type: String
    Description: The project name for cost allocation.
    Default: SecureNotesManager
  UIImageLocation:
    Type: String
    Description: The location of the UI Docker image to use in ECS.
    Default: 123456789012.dkr.ecr.region.amazonaws.com/image:tag
  UIElasticIP:
    Type: String
    Description: The Elastic IP address to use for the UI.
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the ECS cluster will be deployed.

Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub '${AppName}-cluster'
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  APIECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: !Sub '${AppName}-service'
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt ClusterSecurityGroup.GroupId
          Subnets:
            - !Ref ClusterSubnetA
              !Ref ClusterSubnetB
      TaskDefinition: !Ref APIECSTaskDefinition
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  APIECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Command:
            - "/bin/sh"
            - "./start.sh"
          Essential: true
          Image: !Ref APIImageLocation
          Environment:
            - Name: DATABASE_URL
              Value: !Ref DatabaseUrl
          Name: !Sub '${AppName}-api-task'
          PortMappings:
            - ContainerPort: 5000
              HostPort: 5000
              Protocol: tcp
      Cpu: 1024
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Family: !Sub '${AppName}-api-task-family'
      Memory: 2048
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  APIECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: !Sub '${AppName}-service'
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt ClusterSecurityGroup.GroupId
          Subnets:
            - !Ref ClusterSubnetA
              !Ref ClusterSubnetB
      TaskDefinition: !Ref UIECSTaskDefinition
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  UIECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ContainerDefinitions:
        - Command:
            - "/bin/sh"
            - "./start.sh"
          Essential: true
          Image: !Ref UIImageLocation
          Environment:
            - Name: API_URL
              Value: !Ref APIElasticIP
          Name: !Sub '${AppName}-ui-task'
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000
              Protocol: tcp
      Cpu: 1024
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Family: !Sub '${AppName}-ui-task-family'
      Memory: 2048
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ECSCluster:
    Description: ECS Cluster ARN
    Value: !GetAtt ECSCluster.Arn
  APIECSService:
    Description: API Service ARN
    Value: !Ref APIECSService
  APIECSTaskDefinition:
    Description: ECS Task Definition ARN
    Value: !Ref APIECSTaskDefinition
  UIECSService:
    Description: UI Service ARN
    Value: !Ref UIECSService
  UIECSTaskDefinition:
    Description: ECS Task Definition ARN
    Value: !Ref UIECSTaskDefinition