AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppName:
    Type: String
    Description: Used to name resources.
    Default: snm-demo
  ProjectName:
    Type: String
    Description: The project name for cost allocation.
    Default: SecureNotesManager
  Environment:
    Type: String
    Description: The environment for cost allocation.
    Default: Development
  KeypairName:
    Type: String
    Description: The name of the keypair to use for the instance.
    Default: SNMKeyPair
  DatabaseElasticIP:
    Type: String
    Description: The Elastic IP address for the database.
  AMI:
    Type: String
    Description: The AMI to use for the instance.
    Default: ami-058bd2d568351da34
  SecurityGroup:
    Type: String
    Description: The security group to use for the instance.
    Default: sg-0a0a0a0a0a0a0a0a0
  SubnetId:
    Type: String
    Description: The subnet to use for the instance.
  DatabaseUsername:
    Type: String
    Description: The username for the database.
    Default: webuser
  DatabasePassword:
    Type: String
    Description: The password for the database.
    Default: CHANGEME
    NoEcho: true

Resources:
  DatabaseInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType: t2.micro
      KeyName: !Ref KeypairName
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: !Ref SubnetId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install and configure PostgreSQL
          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install postgresql

          PG_HBA_CONF="/etc/postgresql/15/main/pg_hba.conf"
          echo "host    all             all             0.0.0.0/0               md5" | sudo tee -a $PG_HBA_CONF

          PGSQL_CONF="/etc/postgresql/15/main/postgresql.conf"
          echo "listen_addresses = '*'" | sudo tee -a $PGSQL_CONF

          sudo -u postgres psql -c "CREATE USER ${DatabaseUsername} WITH PASSWORD '${DatabasePassword}';"
          sudo -u postgres psql -c "CREATE DATABASE note OWNER ${DatabaseUsername};"
          sudo -u postgres psql -c "ALTER ROLE ${DatabaseUsername} CREATEDB;"
          sudo -u postgres psql -d note -c "CREATE TABLE note (id SERIAL PRIMARY KEY, title TEXT, content TEXT);"
          sudo -u postgres psql -d note -c "ALTER TABLE note OWNER TO ${DatabaseUsername};"
          sudo systemctl restart postgresql
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  IPAssociation:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      InstanceId: !Ref DatabaseInstance
      EIP: !Ref DatabaseElasticIP