AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppName:
    Type: String
    Description: Used to name ECR and CodeBuild project.
    Default: snm-demo
  ProjectName:
    Type: String
    Description: The project name for cost allocation.
    Default: SecureNotesManager
  Environment:
    Type: String
    Description: The environment for cost allocation.
    Default: Development
  AWSRegion:
    Type: String
    Description: AWS region
    Default: us-east-1
  CodeCommitRepo:
    Type: String
    Description: CodeCommit repository URL
  DockerHubUsername:
    Type: String
    Description: Docker Hub username
  DockerHubPassword:
    Type: String
    Description: Docker Hub password
  CodeBuildServiceRole:
    Type: String
    Description: ARN of Code Build Service Role
  ECRRepositoryName:
    Type: String
    Description: ECR repository name
  ECRRepositoryURL:
    Type: String
    Description: ECR repository URL

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AppName}-codebuild-project"
      Description: CodeBuild project for building Docker image and running tests
      ServiceRole: !Ref CodeBuildServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        EnvironmentVariables:
          - Name: CODECOMMIT_REPO
            Value: !Ref CodeCommitRepo
          - Name: DOCKER_IMAGE_NAME
            Value: !Ref AppName
          - Name: ECR_REPOSITORY_NAME
            Value: !Ref ECRRepositoryName
          - Name: ECR_REPOSITORY_URL
            Value: !Ref ECRRepositoryURL
          - Name: DOCKERHUB_USERNAME
            Value: !Ref DockerHubUsername
          - Name: DOCKERHUB_PASSWORD
            Value: !Ref DockerHubPassword
          - Name: AWS_REGION
            Value: !Ref AWSRegion
      Source:
        Type: CODECOMMIT
        Location: !Ref CodeCommitRepo
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                docker: 20
              commands:
                - echo Setting up environment variables...
                - export ECR_REPOSITORY_NAME=$ECR_REPOSITORY_NAME
                - export ECR_REPOSITORY_URL=$ECR_REPOSITORY_URL
                - export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
                - export DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD
                - export AWS_REGION=$AWS_REGION
            pre_build:
              commands:
                - echo Logging in to Docker Hub...
                - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              finally:
                - echo Cleanup environment variables...
                - unset AWS_REGION AWS_ACCOUNT_ID ECR_REPOSITORY_NAME ECR_REPOSITORY_URL DOCKERHUB_USERNAME DOCKERHUB_PASSWORD AWS_REGION
            build:
              commands:
                - echo Building Docker image...
                - docker build -t $DOCKER_IMAGE_NAME .
            post_build:
              commands:
                - echo Pushing Docker image to Amazon ECR...
                - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
                - docker tag $DOCKER_IMAGE_NAME:latest $ECR_REPOSITORY_URL:latest
                - docker push $ECR_REPOSITORY_URL:latest
      TimeoutInMinutes: 60
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  CodeBuildProjectARN:
    Description: CodeBuild project ARN
    Value: !GetAtt CodeBuildProject.Arn
    Export:
      Name: !Sub '${AppName}-codebuild-project-arn'
