AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppName: 
    Type: String
    Description: Used to name resources.
  Environment:
    Type: String
    Description: Environment name for cost allocation.
    Default: Development
  ProjectName:
    Type: String
    Description: Project name for cost allocation.
    Default: SecureNotesManager

Resources:
  APICodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-api-repository
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectName
          Value: !Ref ProjectName

  APIECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-api-repository
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectName
          Value: !Ref ProjectName

  UICodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-ui-repository
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectName
          Value: !Ref ProjectName

  UIECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-ui-repository
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectName
          Value: !Ref ProjectName

Outputs:
  APICodeCommitRepositoryURL:
    Description: CodeCommit repository URL
    Value: !GetAtt APICodeCommitRepository.CloneUrlHttp
    Export:
      Name: !Sub ${AppName}-api-cc-repository-url
  APIECRRepositoryURL:
    Description: ECR repository URL
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}-api-repository
    Export:
      Name: !Sub ${AppName}-api-ecr-repository-url
  UICodeCommitRepositoryURL:
    Description: CodeCommit repository URL
    Value: !GetAtt UICodeCommitRepository.CloneUrlHttp
    Export:
      Name: !Sub ${AppName}-ui-cc-repository-url
  UIECRRepositoryURL:
    Description: ECR repository URL
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}-ui-repository
    Export:
      Name: !Sub ${AppName}-ui-ecr-repository-url