AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppName: 
    Type: String
    Description: Used to name resources.
  ProjectName:
    Type: String
    Description: Project name for cost allocation.
    Default: SecureNotesManager
  Environment:
    Type: String
    Description: Environment name for cost allocation.
    Default: Development

Resources:
  CodeCommitRepositoryAPI:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-api-repository
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  ECRRepositoryAPI:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-api-repository
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  CodeCommitRepositoryUI:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-ui-repository
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  ECRRepositoryUI:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-ui-repository
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  CodeCommitRepositoryURLAPI:
    Description: CodeCommit repository URL
    Value: !GetAtt CodeCommitRepositoryAPI.CloneUrlHttp
    Export:
      Name: !Sub ${AppName}-api-cc-repository-url
  ECRRepositoryURLAPI:
    Description: ECR repository URL
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}-api-repository
    Export:
      Name: !Sub ${AppName}-api-ecr-repository-url
  CodeCommitRepositoryURLUI:
    Description: CodeCommit repository URL
    Value: !GetAtt CodeCommitRepositoryUI.CloneUrlHttp
    Export:
      Name: !Sub ${AppName}-ui-cc-repository-url
  ECRRepositoryURLUI:
    Description: ECR repository URL
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}-ui-repository
    Export:
      Name: !Sub ${AppName}-ui-ecr-repository-url