Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-codepipeline-bucket
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
            NoncurrentVersionTransitions:
              - StorageClass: GLACIER
                TransitionInDays: 60
