AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SubnetCIDR:
    Type: String
    Description: The CIDR range for the subnet.
    Default: 172.31.112.0/20
  ProjectName:
    Type: String
    Description: Project name for cost allocation.
    Default: SecureNoteManager
  Environment:
    Type: String
    Description: Environment name for cost allocation.
    Default: Development

Resources:
  ECSClusterSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPCId
      CidrBlock: !Ref SubnetCIDR
      AvailabilityZone: us-east-1a
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ECSClusterSubnetId:
    Description: Subnet ID for the ECS cluster
    Value: !Ref ECSClusterSubnet
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ecs-cluster-subnet-id'