AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String
    Description: Project name for cost allocation.
    Default: SecureNoteManager
  Environment:
    Type: String
    Description: Environment name for cost allocation.
    Default: Development
  UISecurityGroup:
    Type: String
    Description: The ID of the security group for the UI.
  APISecurityGroup:
    Type: String
    Description: The ID of the security group for the API.

Resources:
  # NETWORKS
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-vpc'

  ECSClusterSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      AvailabilityZone: us-east-1a
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # NETWORK LOAD BALANCERS
  UIServiceNetworkLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-ui-nlb'
      Scheme: internet-facing
      Subnets:
        - !Ref ECSClusterSubnet
      SecurityGroups:
        - !GetAtt UISecurityGroup.GroupId
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  APIServiceNetworkLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-api-nlb'
      Scheme: internet-facing
      Subnets:
        - !Ref ECSClusterSubnet
      SecurityGroups:
        - !GetAtt APISecurityGroup.GroupId
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ELASTIC IPS
  PostgresElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
          
  NginxElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  UIElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  APIElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref MyVPC
    Export:
      Name: !Sub '${ProjectName}-${Environment}-vpc-id'
  ECSClusterSubnet:
    Description: Subnet ID for the ECS cluster
    Value: !Ref ECSClusterSubnet
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ecs-cluster-subnet-id'
  PostgresElasticIP:
    Description: Elastic IP for the Postgres EC2 instance
    Value: !Ref PostgresElasticIP
    Export:
      Name: !Sub '${ProjectName}-${Environment}-postgres-elastic-ip'
  NginxElasticIP:
    Description: Elastic IP for the Nginx EC2 instance
    Value: !Ref NginxElasticIP
    Export:
      Name: !Sub '${ProjectName}-${Environment}-nginx-elastic-ip'
  UIElasticIP:
    Description: Elastic IP for the UI ECS service
    Value: !Ref UIElasticIP
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ui-elastic-ip'
  APIElasticIP:
    Description: Elastic IP for the API ECS service
    Value: !Ref APIElasticIP
    Export:
      Name: !Sub '${ProjectName}-${Environment}-api-elastic-ip'
  UIServiceNetworkLoadBalancer:
    Description: Network load balancer for the UI
    Value: !Ref UIServiceNetworkLoadBalancer
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ui-nlb'
  APIServiceNetworkLoadBalancer:
    Description: Network load balancer for the API
    Value: !Ref APIServiceNetworkLoadBalancer
    Export:
      Name: !Sub '${ProjectName}-${Environment}-api-nlb'