AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppName:
    Type: String
    Description: Used to name resources.
  ProjectName:
    Type: String
    Description: Project name for cost allocation.
    Default: SecureNoteManager
  Environment:
    Type: String
    Description: Environment name for cost allocation.
    Default: Dev
  DockerUsername:
    Type: String
    Description: Username for the secret
  DockerPassword:
    Type: String
    Description: Password for the secret
    NoEcho: true
  DatabaseUsername:
    Type: String
    Description: Username for the secret
    Default: webuser
  DatabasePassword:
    Type: String
    Description: Password for the secret
    Default: CHANGEME
    NoEcho: true

Resources:
  DockerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MySecret
      Description: My secret
      SecretString:
        Fn::Sub:
          - |
            {
              "username": "${DockerUsername}",
              "password": "${DockerPassword}"
            }
          - Username: !Ref Username
            Password: !Ref Password
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub '${AppName}-docker-secret'
        
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: DatabaseSecret
      Description: Database secret
      SecretString:
        Fn::Sub:
          - |
            {
              "username": "${DatabaseUsername}",
              "password": "${DatabasePassword}"
            }
          - Username: !Ref DatabaseUsername
            Password: !Ref DatabasePassword
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub '${AppName}-database-secret'

Outputs:
  DockerSecretArn:
    Description: The ARN of the Docker secret.
    Value: !Ref DockerSecret
    Export:
      Name: !Sub '${AppName}-docker-secret-arn'
  DatabaseSecretArn:
    Description: The ARN of the database secret.
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub '${AppName}-database-secret-arn'