AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppName:
    Type: String
    Description: Used to name resources.
  DatabaseUsername:
    Type: String
    Description: Username for the secret
    Default: webuser
  DatabasePassword:
    Type: String
    Description: Password for the secret
    Default: CHANGEME
    NoEcho: true
  DockerHubUsername:
    Type: String
    Description: Username for the secret
  DockerHubPassword:
    Type: String
    Description: Password for the secret
    NoEcho: true
  Environment:
    Type: String
    Description: Environment name for cost allocation.
    Default: Development
  ProjectName:
    Type: String
    Description: Project name for cost allocation.
    Default: SecureNoteManager

Resources:
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: DatabaseSecret
      Description: Database secret
      SecretString:
        Fn::Sub:
          - |
            {
              "username": "${DatabaseUsername}",
              "password": "${DatabasePassword}"
            }
          - Username: !Ref DatabaseUsername
            Password: !Ref DatabasePassword
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub '${AppName}-database-secret'

  DockerHubSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: DockerHubSecret
      Description: My secret
      SecretString:
        Fn::Sub:
          - |
            {
              "username": "${DockerHubUsername}",
              "password": "${DockerHubPassword}"
            }
          - Username: !Ref DockerHubUsername
            Password: !Ref DockerHubPassword
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub '${AppName}-dockerhub-secret'

Outputs:
  DatabaseSecretArn:
    Description: The ARN of the database secret.
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub '${AppName}-database-secret-arn'
  DockerHubSecretArn:
    Description: The ARN of the DockerHub secret.
    Value: !Ref DockerHubSecret
    Export:
      Name: !Sub '${AppName}-dockerhub-secret-arn'