AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Username:
    Type: String
    Description: Username for the secret
  Password:
    Type: String
    Description: Password for the secret
    NoEcho: true

Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MySecret
      Description: My secret
      SecretString:
        Fn::Sub:
          - |
            {
              "username": "${Username}",
              "password": "${Password}"
            }
          - Username: !Ref Username
            Password: !Ref Password
      Tags:
        - Key: Environment
          Value: Production
