AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  IngressCIDR:
    Type: String
    Description: The CIDR range for inbound access. (Point to the Internet.)
    Default: 0.0.0.0/0
  ReverseProxyElasticIP:
    Type: String
    Description: The Elastic IP address for the reverse proxy.
  UIElasticIP:
    Type: String
    Description: The Elastic IP address for the UI.
  APIElasticIP:
    Type: String
    Description: The Elastic IP address for the API.
  KeypairName:
    Type: String
    Description: The name of the EC2 key pair to associate with the instance.
    Default: SNMKeypair
  AMI:
    Type: String
    Description: The AMI to use for the instance.
    Default: ami-058bd2d568351da34
  SecurityGroup:
    Type: String
    Description: The security group to use for the instance.
    Default: sg-0a0a0a0a0a0a0a0a0
  ProjectName:
    Type: String
    Description: The project name for cost allocation.
    Default: SecureNotesManager
  Environment:
    Type: String
    Description: The environment for cost allocation.
    Default: Development

Resources:
  ReverseProxyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType: t2.micro
      KeyName: !Ref KeypairName
      SecurityGroupIds:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update and install Nginx
          sudo apt-get update
          sudo apt-get install -y nginx

          # Display Nginx version
          sudo nginx -v

          # Create NGINX configuration file
          echo 'server {
              listen 80;
              server_name ${UIElasticIP};

              location / {
                  proxy_pass http://${UIElasticIP}:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
            }

            server {
              listen 5000;
              server_name ${APIElasticIP};

              location / {
                  proxy_pass http://${APIElasticIP}:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
            }' | sudo tee /etc/nginx/sites-available/default

          # Reload Nginx to apply changes
          sudo nginx -s reload

          # Display status after setup
          sudo systemctl status nginx.service
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  IPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref ReverseProxyInstance
      EIP: !Ref ReverseProxyElasticIP
